export const ADD_CURRENT_POST = 'ADD_CURRENT_POST';
export const CLEAR_CURRENT_POST = 'CLEAR_CURRENT_POST';
export const DELETE_POST = 'DELETE_POST';
export const ADD_CURRENT_PROFILE = 'ADD_CURRENT_PROFILE';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
